using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using UnityEngine.UI;

/* This class contains the proper methods to save the relevant information in the DB. The "Insert"
methods perform basic operations in the DB. The "Save" methods collect information in the unity
objects and insert the data into de DB calling the "Insert" methods. */
public class PoseDBManager : MonoBehaviour {
	// Url of the "InsertGenericData.php" file for this EmoPose application
	private string url = "http://webdiis.unizar.es/~ivangmg/emopose/InsertGenericData.php";
	// Url of the "InsertGenericData.php" file for this EmoPose application
	//private string urlPost = "http://webdiis.unizar.es/~ivangmg/emopose/InsertGenericDataPost.php";
	// Reference to the generic DB manager
	public GenericDBManager dbManager;
	// A pose writer to perform the writing
	private PoseWriter poseWriter;
	// The last result datetime. It will be associated with the following related actions.
	// It uses the URL string format
	private string lastResultDatetime;
	///// References for obtaing data from different places
	public GameControllerClassifier gameControllerClassifier;
	public PoseStopwatch poseStopWatch;
	//public ToggleGroup selectedEmoToggleGroup; // In the code any toggle button of the SelectedEmoCanvas (AngryToggle Group)
	public SelectEmoController selectedEmoController;

	// Use this for initialization
	void Start () {
		//dbManager = new GenericDBManager (url);
		poseWriter = new PoseWriter ();
		dbManager.SetUrl (url);
		dbManager.SaveDeviceInfo ("EmoPose");
		//InsertTest ("prueba21");
		//InsertResult (24, Emotion.Happy,1.3f);
		//InsertPose(new Pose());
		//InsertPoseCase(new PoseCase(new Pose(), Emotion.None));
		//dbManager.InsertData ("EmoPoseResult", "11,'happiness'");
	}
	// Insert classifier results adding the user date
	public void InsertResult(int elapsedTime, Emotion emotion, float distance){
		lastResultDatetime = dbManager.GetUserDatetime ();
		dbManager.InsertData ("EmoPoseResult",
			"'"+SystemInfo.deviceUniqueIdentifier+"'"+","+
			lastResultDatetime+","+
			elapsedTime+","+
			"'"+emotion+"'"+","+
			distance);
	}
	// For basic tests
	public void InsertTest(string content){
		dbManager.InsertData ("EmoPosePrueba", "'"+content+"'");
	}
	// Insert a pose associating it with the last result datetime
	public void InsertPose(Pose pose){
		dbManager.InsertData("EmoPosePose",
			"'"+SystemInfo.deviceUniqueIdentifier+"'"+","+
			lastResultDatetime+","+
			"'"+poseWriter.PoseToString(pose)+"'");
	}
	// Insert the feedback of the user, wrong (0) or right(1) 
	public void InsertFeedback(int isCorrect){
		dbManager.InsertData("EmoPoseFeedback",
			"'"+SystemInfo.deviceUniqueIdentifier+"'"+","+
			lastResultDatetime+","+
			isCorrect);
	}
	// Insert a pose case (i.e. the emotion with a pose) associating it with the last 
	// result datetime
	public void InsertPoseCase(PoseCase poseCase){
		dbManager.InsertData("EmoPoseCase",
			"'"+SystemInfo.deviceUniqueIdentifier+"'"+","+
			lastResultDatetime+","+
			"'"+poseCase.emotion+"'"+","+
			"'"+poseWriter.PoseToString(poseCase.pose)+"'");
	}
	// Insert the distane to the nearest case the emotion manually selected by the user
	public void InsertDistanceSelectedEmo(Emotion emotion, float distance){
		dbManager.InsertData("EmoPoseDistanceSelectedEmo",
			"'"+SystemInfo.deviceUniqueIdentifier+"'"+","+
			lastResultDatetime+","+
			"'"+emotion+"'"+","+
			distance);
	}


	// It saves the result data and the pose obtaining the data from the other 
	// components
	public void SaveResult(){
		InsertResult(poseStopWatch.lastTimeElapsedSeconds,
			gameControllerClassifier.GetLastOutputtedEmotion(),
			gameControllerClassifier.GetLastDistance());
		InsertPose (gameControllerClassifier.GetLastUserPose ());
	}
	// It saves the feedback where isCorrect can be 0 (wrong) or 1 (right). If
	// correct, it saves a new pose case
	public void SaveFeedback(int isCorrect){
		InsertFeedback (isCorrect);
		if (isCorrect > 0) {
			PoseCase poseCase = new PoseCase (gameControllerClassifier.GetLastUserPose (),
				                    gameControllerClassifier.GetLastOutputtedEmotion ());
			InsertPoseCase (poseCase);
		}			
	}
	// It saves the pose case with the emotion selected manually by the user and the 
	// pose generated by the user. It also saves the distance to the selected emotion
	//
	public void SaveSelectedEmotion(){
		// Get the selected emo
		Emotion selectedEmo=selectedEmoController.GetSelectedEmo();
		//selectedEmo = Emotion.
		// Save the pose case considering selected Emo
		PoseCase poseCase = new PoseCase (gameControllerClassifier.GetLastUserPose (),
			selectedEmo);
		InsertPoseCase (poseCase);
		// Insert the distance to the selected emo
		float distance = gameControllerClassifier.GetDistanceLastPoseToEmo(selectedEmo);
		InsertDistanceSelectedEmo (selectedEmo, distance);
	}



}


/// NOT USED

/*IEnumerator<Toggle> enumerator = selectedEmoToggleGroup.ActiveToggles().GetEnumerator();
		enumerator.MoveNext();
		Toggle selectedToggle =  enumerator.Current; 
		Emotion selectedEmo;
		if (selectedToggle == null)
			selectedEmo = Emotion.None;
		else {
			string strEmo = selectedToggle.name;
			selectedEmo = (Emotion)Enum.Parse (typeof(Emotion), strEmo);
		}
		*/

// Convert.ToInt32(isCorrect)

//dbManager.urlPost = urlPost;
