# 0 = no PDF
# 1 = pdflatex
# 2 = ps2pdf
# 3 = dvipdf
# 4 = lualatex
# 5 = xelatex
$pdf_mode = 5;
$out_dir = 'out';
$aux_dir = 'tmp';

# Clean up intermediate files after successful build
$clean_ext = 'synctex.gz';

# Number of times to run latex
$max_repeat = 5;
# Use bibtex if needed
$bibtex_use = 2;
